---
title: "Amazon"
format: html
editor: visual
---

#notes

```{r}
# lcd /mnt/c/Users/riley/Documents/GitHub/Stat\ 348/Amazon
```

# Load Libraries

```{r}
library(tidyverse)
library(tidymodels)
library(vroom)
library(naivebayes)
library(embed)
library(discrim)
```

# Import Data

```{r}
train <- vroom("~/GitHub/Stat 348/Amazon/Data/train.csv")
test <- vroom("~/GitHub/Stat 348/Amazon/Data/test.csv")
```

# Recipe

```{r}
train <- train %>%
  mutate(ACTION = as.factor(ACTION))

amazon_recipe <- recipe(ACTION ~ ., data = train) %>%
  step_string2factor(all_nominal_predictors()) %>%
  step_other(all_nominal_predictors(), threshold = 0.001) %>%
  step_lencode_mixed(all_nominal_predictors(), outcome = vars(ACTION)) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_pca(all_predictors(), threshold=.9)

amazon_prep <- prep(amazon_recipe)
amazon_train <- bake(amazon_prep, new_data = NULL)
amazon_test <- bake(amazon_prep, new_data = test)


```

Models

```{r}
model <- naive_Bayes(Laplace=tune(), smoothness=tune()) %>%
set_mode("classification") %>%
set_engine("naivebayes") 

```

Workflow

```{r}
wf <- workflow() %>%
  add_recipe(amazon_recipe) %>%
  add_model(model)

```

Tune

```{r}
tune_grid <- grid_regular(
  Laplace(range = c(0, 1)),
  smoothness(range = c(.1,2))
  , levels = 10)
folds <- vfold_cv(train, v = 6)


## Run the CV
CV_results <- wf %>%
  tune_grid(
    resamples = folds,
    grid = tune_grid,
    metrics = metric_set(roc_auc, accuracy)
  )
```

# Best model

```{r}
bestTune <- CV_results %>%
  select_best(metric = "roc_auc")
```

Predictions

```{r}
final_wf <- wf %>%
  finalize_workflow(bestTune) %>%
  fit(data = train)

amazon_predictions <- predict(final_wf,
new_data = test,
type= "prob") 
```

Print

```{r}
kaggle_submission <- amazon_predictions |>
  bind_cols(test) |> 
  select(id, .pred_1) |>
  rename(ACTION = .pred_1) 

## Write out the file
vroom_write(x = kaggle_submission,
            file = "~/GitHub/Stat 348/Amazon/Data/KaggleSub/Kaggle_Bayes_PCA.csv",
            delim = ",")
```
